@WebApi_HostAddress = http://localhost:8080

POST {{WebApi_HostAddress}}/api/empresas
Content-Type: application/json
Accept: application/json

{
  "idempresa": 10,
  "nome": "Amazon Prime",
  "email": "contato@amazon.com",
  "cnpj": "12.345.678/0001",
  "segmento": "E-commerce",
  "dataFundacao": "1994-07-05"
}

###
GET {{WebApi_HostAddress}}/api/empresas
Content-Type: application/json
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/empresas/1
Content-Type: application/json
Accept: application/json

###

PUT {{WebApi_HostAddress}}/api/empresas/1
Content-Type: application/json
Accept: application/json

{
  "nome": "Amazon Brasil",
  "email": "contato@amazon.com",
  "cnpj": "12.345.678/0001-90",
  "segmento": "E-commerce",
  "dataFundacao": "1994-07-05"
}

###
DELETE {{WebApi_HostAddress}}/api/empresas/1
Content-Type: application/json
Accept: application/json

