@WebApi_HostAddress = http://localhost:8080

POST {{WebApi_HostAddress}}/api/empresas
Content-Type: application/json
Accept: application/json

{
  "idempresa": 110,
  "nome": "FIAP",
  "email": "contato@fiap.com",
  "cnpj": "12.345.678/0001",
  "segmento": "Educação",
  "dataFundacao": "1994-07-05"
}

###
GET {{WebApi_HostAddress}}/api/empresas
Content-Type: application/json
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/empresas/110
Content-Type: application/json
Accept: application/json

###

PUT {{WebApi_HostAddress}}/api/empresas/110
Content-Type: application/json
Accept: application/json

{
  "nome": "FIAP Faculdade",
  "email": "contato@fiap.com",
  "cnpj": "12.345.678/0001",
  "segmento": "Educação Superior",
  "dataFundacao": "1994-07-05"
}

###
DELETE {{WebApi_HostAddress}}/api/empresas/110
Content-Type: application/json
Accept: application/json

